name: Update Profile & Daily Quote

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run quote updater script
        run: node index.js

      - name: Commit and push changes
        run: |
          git config --global user.email "hoangvu2k4cmg@gmail.com"
          git config --global user.name "tranhohoangvu"
          git add README.md
          git commit -m "Update Daily Quote [skip ci]" || echo "No changes to commit"
          git push
